services:
  db:
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      interval: 1s
      timeout: 1s
      retries: 1

  app-test:
    build:
      context: ./backend
      target: test
    environment:
      DB_URL: "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable"
      GOCACHE: /tmp/.cache
    volumes:
      - ./backend/:/app
    command: tail -f /dev/null
    depends_on:
      db:
        condition: service_healthy

  frontend-test:
    build:
      context: ./frontend
      target: test
    volumes:
      - ./frontend/:/app
      - /app/node_modules

volumes:
  postgres_test_data:
