services:
  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app-dev:
    build:
      context: ./backend
      target: dev
    user: "${UID}:${GID}"
    ports:
      - "8080:8080"
    environment:
      DB_URL: "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable"
      GOCACHE: /tmp/.cache
    volumes:
      - ./backend/:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
